---
- name: Pull docker image from dockerhub
  hosts: all
  tasks:
    - name: Pull docker image
      docker_image:
        name: hansal21/miniproject
        source: pull
    - name: running container
      shell: docker run -it hansal21/miniproject:latest